language: java

jdk:
  - openjdk11

# The trusty build environment allows for more memory, see https://docs.travis-ci.com/user/reference/overview/
dist: trusty

env:
  global:
    - MAVEN_OPTS="-Xmx6G"

script:
  - mvn test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e

cache:
  directories:
  - $HOME/.m2
